### ISSUE TITLE
Milestones & Issue tags

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#263]
I'd love to be able to contribute more meaningfully (+ encourage others to contribute more) to Relay! Most of the outside contributions so far are have been small; mostly fixing bugs, documentation issues, or build/release issues. 

It would be great if we could set up some milestones (or similar) on GitHub so that we can get an idea of not just what is already being worked on by FB, but also a sense of any bigger or longer term projects that the community can contribute to as well.

The former can partially be gleaned from some existing GitHub issues, like...

* [ ] Server-side rendering hooks #136 (@voideanvalue)
* [ ] Client-side schema #114 (@josephsavona)
* [ ] Better intro tutorials #6 (@steveluscher)
* [ ] Support root fields w/o node mapping #112 (?)
* [ ] Better developer tools (@kassens)
* [ ] Support deferred queries (@wincent)

The latter is harder, but probably looks something like:

* [ ] Improved mutation config/error handling #231 #261
* [ ] Easier to use Babel plugin #206
* [ ] ...more

The _Help Wanted_ tags that @yungsters has been adding seem like a good step in this direction, though.

**Comment by wincent** [comment]
> I'd love to be able to contribute more meaningfully (+ encourage others to contribute more) to Relay!

Yes, we'd love that too. Thanks for bringing this up!

You have a pretty good list there of what we're working on internally. The one or two things that seems to be missing is better developer tools (@kassens) and porting our already-existing internal support for deferred queries (@wincent).

I am not sure if we're ready to start planning at the milestone level (the project is still so young, that we expect to be doing regular releases at a cadence of about every two weeks or so, and a lot of this early work is reactive/responsive to emergent needs), but doing a better job with labels is something we should do right now.

I also think a bit more of a (tentative) roadmap document could be useful.

**Comment by devknoll** [comment]
> I also think a bit more of a (tentative) roadmap document could be useful.

I think that this + labels would be a great place to start in the interim!

**Comment by wincent** [comment]
I've split off #284 to track producing a roadmap. The label thing is a bit fuzzier, but I'm going through now making sure that everything is properly labeled, and the other team members are already CC'd here, so I think we can close this now.

Let us know if you have any concrete suggestions for labels that you think we should start using but aren't yet, or labels which we're misusing or could use better.

And thanks once again for contributing and helping us improve our processes.
