### ISSUE TITLE
[epic] enable Rust compiler for OSS

### ISSUE THREAD

**Issue by kassens** [facebook/relay#3180]
This issue collects what I think is missing to update the Relay compiler to the Rust version in OSS. If someone want's to give any of this a shot, please comment here!

- [x] Typescript generator as something configured in the compiler config.json
- [x] Non-watchman file source. Currently we convert the directories in `config.json` into a watchman query for watch mode and simple builds. This was designed with non-watchman in mind and it should be possible to build out something that uses a different file-crawler and maybe file watcher crate. This is not strictly required, but I think removing this external required dependency would be nice. (Details in #3193)
- [x] Figure out how we deploy a pre-build binary using npm. The `flow-bin` package might be a good inspiration as that somehow loads the binary for that version on first use. (Details/discussion in #3194)
- [x] Some missing config options in how types are generated (Details/discussion in #3195)
- [x] Refine Typescript generation (Details/discussion in #3196)
- [ ] https://github.com/facebook/relay/issues/3438
- [x] https://github.com/facebook/relay/issues/3437
- [x] Look at assumptions of using hg
- [x] Figure out situation with required variables with default values (see: https://github.com/facebook/relay/pull/3612 )
- [x] Documentation/Blog Post about the release of new version of the compiler
- [x] Deprecate JS version of the compiler
- [x] #3627
- [ ] Fix issues listed here: https://github.com/vincentriemer/new-relay-compiler-issues-repro

**Comment by kassens** [comment]
@MaartenStaa made a huge leap start on this with #3182!

I understand there's a few improvements we can make to the types still by copying more what the JS OSS typescript generator produces: https://github.com/relay-tools/relay-compiler-language-typescript/blob/e1b092f081d4e816ecd17fb0d3b4e62cdf3db917/test/__snapshots__/TypeScriptGenerator-test.ts.snap

I'll file separate issues for the remaining checkboxes.

**Comment by kassens** [comment]
A good intro way to contribute is #3199 to convert the runtime unit tests to use artifacts generated by the Rust compiler. More details in there.

**Comment by alunyov** [comment]
Thanks @stale. I think we still need the issue. I'm looking at converting the rest of the tests. It may take a while, but we'll see.

**Comment by alunyov** [comment]
>  Non-watchman file source. Currently we convert the directories in config.json into a watchman query for watch mode and simple builds. This was designed with non-watchman in mind and it should be possible to build out something that uses a different file-crawler and maybe file watcher crate. This is not strictly required, but I think removing this external required dependency would be nice. (Details in #3193)

One more point on why we may need to work on this: the current watchman client for rust doesn't work on Windows (I was testing it with github actions for windows: https://github.com/alunyov/relay/runs/2104656440?check_suite_focus=true). So we may add something like: https://github.com/notify-rs/notify in OSS.

**Comment by maraisr** [comment]
Can we also look at supporting "watch-mode" for OSS?

Currently we're forced to use `hg`??

https://github.com/facebook/relay/blob/aeac451820bc9ce732d4f225664853aa763d3f6f/compiler/crates/relay-compiler/src/file_source/watchman_file_source.rs#L391

**Comment by TrySound** [comment]
Will rust compiler support es modules? Looks like it was not implemented.
https://github.com/facebook/relay/blob/main/compiler/crates/relay-codegen/src/js_module_format.rs

**Comment by maraisr** [comment]
@TrySound do you actually know where that `js_module` is actually used? Afaik it makes no difference? Or perhaps just with the `langauge: "typescript"` it isnt. I get `import { ConcreteRequest } from 'relay-runtime';` in my `__genearted__`. 

Or is that more about `JSDepedency` aka `@module`?

**Comment by alunyov** [comment]
> Can we also look at supporting "watch-mode" for OSS?
> 
> Currently we're forced to use `hg`??
> 
> https://github.com/facebook/relay/blob/aeac451820bc9ce732d4f225664853aa763d3f6f/compiler/crates/relay-compiler/src/file_source/watchman_file_source.rs#L391

Oh, yes, this is something that we need to fix. `hg` is definitely not a requirement for a watch mode.

**Comment by mrtnzlml** [comment]
Hi, I would like to propose to include the following issues/bugs into the list as well:

- https://github.com/facebook/relay/issues/3438
- https://github.com/facebook/relay/issues/3437

Thanks! 😎

**Comment by alunyov** [comment]
`hg` issue fixed here: https://github.com/facebook/relay/commit/d3364605f932b86edbd70d794733b4524d1d053f

**Comment by huv1k** [comment]
There is a problem with `@argumentDefinitions`  and `defaultValue` for `@refetchable` connections. Error is bellow:

```
    3 │       @argumentDefinitions(
    4 │         first: { type: "Int!", defaultValue: 2 }
      │                                              ^
    5 │         after: { type: "String" }

[ERROR] ✖︎ Non-nullable variable 'first' has a default value.
```

**Comment by zth** [comment]
@huv1k this is actually a proper validation that has started working with the new compiler. So, the solution is to go ahead and remove the default value, or make the argument optional by removing the `!` from the definition.

**Comment by alunyov** [comment]
v13 released. Closing this in favor of https://github.com/facebook/relay/issues/3749
